# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'VariationStockChallenge' do
  use_frameworks!

  flutter_application_path = '../stock_variation_module'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)

  post_install do |installer|
    flutter_post_install(installer) if defined?(flutter_post_install)
  end

end
